/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package futsalbookingsystem.view;

import futsalbookingsystem.view.AccDeletion;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class SettingView extends javax.swing.JFrame {
    private String userEmail;

    /**
     * Creates new form SettingView
     */
    public SettingView(String userEmail) {
        this.userEmail = userEmail;
        initComponents();

        DeleteAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt){
                AccDeletion accDeletion = new AccDeletion(userEmail);
                accDeletion.setVisible(true);
                SettingView.this.dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DashboardBtn = new javax.swing.JButton();
        EventBtn = new javax.swing.JButton();
        BookingBtn = new javax.swing.JButton();
        HostoryBtn = new javax.swing.JButton();
        SettingBtn = new javax.swing.JButton();
        UpdateInfoBtn = new javax.swing.JButton();
        ViewprofileBtn = new javax.swing.JButton();
        ChangePasswordBtn = new javax.swing.JButton();
        DeleteAccountBtn = new javax.swing.JButton();
        RatingBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nutgmegz");

        DashboardBtn.setBackground(new java.awt.Color(217, 217, 217));
        DashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DashboardBtn.setText("Dashboard");
        DashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardBtnActionPerformed(evt);
            }
        });

        EventBtn.setBackground(new java.awt.Color(217, 217, 217));
        EventBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        EventBtn.setText("Event");
        EventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventBtnActionPerformed(evt);
            }
        });

        BookingBtn.setBackground(new java.awt.Color(217, 217, 217));
        BookingBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        BookingBtn.setText("Booking");
        BookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingBtnActionPerformed(evt);
            }
        });

        HostoryBtn.setBackground(new java.awt.Color(217, 217, 217));
        HostoryBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        HostoryBtn.setText("History");
        HostoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HostoryBtnActionPerformed(evt);
            }
        });

        SettingBtn.setBackground(new java.awt.Color(217, 217, 217));
        SettingBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SettingBtn.setText("Setting-");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EventBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HostoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SettingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(DashboardBtn)
                .addGap(18, 18, 18)
                .addComponent(EventBtn)
                .addGap(18, 18, 18)
                .addComponent(BookingBtn)
                .addGap(18, 18, 18)
                .addComponent(HostoryBtn)
                .addGap(18, 18, 18)
                .addComponent(SettingBtn)
                .addGap(60, 60, 60))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 570));

        UpdateInfoBtn.setBackground(new java.awt.Color(217, 217, 217));
        UpdateInfoBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        UpdateInfoBtn.setText("Update Information");
        UpdateInfoBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        UpdateInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInfoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 330, 120));

        ViewprofileBtn.setBackground(new java.awt.Color(217, 217, 217));
        ViewprofileBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ViewprofileBtn.setText("View Profile");
        ViewprofileBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ViewprofileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewprofileBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewprofileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 330, 120));

        ChangePasswordBtn.setBackground(new java.awt.Color(217, 217, 217));
        ChangePasswordBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ChangePasswordBtn.setText("Change Password");
        ChangePasswordBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ChangePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ChangePasswordBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 330, 120));

        DeleteAccountBtn.setBackground(new java.awt.Color(217, 217, 217));
        DeleteAccountBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DeleteAccountBtn.setText("Delete Account");
        DeleteAccountBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        DeleteAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAccountBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteAccountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 330, 120));

        RatingBtn.setBackground(new java.awt.Color(217, 217, 217));
        RatingBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RatingBtn.setText("Rating");
        RatingBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        RatingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RatingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 330, 120));

        LogoutBtn.setBackground(new java.awt.Color(217, 217, 217));
        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 330, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        jLabel2.setText("Setting");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/futsalbookingsystem/imagepicker/Background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardBtnActionPerformed
        // TODO add your handling code here:
        DashboardView dashboardView = new DashboardView(userEmail);
        dashboardView.setVisible(true);
        dispose();
        
        dispose();
    }//GEN-LAST:event_DashboardBtnActionPerformed

    private void EventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventBtnActionPerformed
        // TODO add your handling code here:
        EventView eventView = new EventView(userEmail);
        eventView.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_EventBtnActionPerformed

    private void BookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingBtnActionPerformed
        // TODO add your handling code here:
        BookingView bookingView = new BookingView(userEmail);
        bookingView.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_BookingBtnActionPerformed

    private void HostoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HostoryBtnActionPerformed
        // TODO add your handling code here:
        HistoryView historyView  = new HistoryView(userEmail);
        historyView.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_HostoryBtnActionPerformed

    private void ChangePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordBtnActionPerformed
        // TODO add your handling code here:
        ChangeKnownPasswordView changePasswordView = new ChangeKnownPasswordView(userEmail);
        changePasswordView.setVisible(true);
        dispose();
    }//GEN-LAST:event_ChangePasswordBtnActionPerformed

    private void UpdateInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInfoBtnActionPerformed
        // TODO add your handling code here:
        UpdateAccountView updateView = new UpdateAccountView(userEmail);
        updateView.setVisible(true);
        dispose();
    }//GEN-LAST:event_UpdateInfoBtnActionPerformed

    private void DeleteAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAccountBtnActionPerformed
        // TODO add your handling code here:
        AccDeletion accdeletionView  = new AccDeletion(userEmail);
        accdeletionView.setVisible(true);
        dispose();
        
        dispose();
    }//GEN-LAST:event_DeleteAccountBtnActionPerformed

    private void ViewprofileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewprofileBtnActionPerformed
        // TODO add your handling code here:
        ViewProfileView viewprofileView = new ViewProfileView(userEmail);
        viewprofileView.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_ViewprofileBtnActionPerformed

    private void RatingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatingBtnActionPerformed
        // TODO add your handling code here:
        RatingView ratingView = new RatingView(userEmail);
        ratingView.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_RatingBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
//        LoginView loginView = new LoginView();
//        loginView.show();
//        dispose();
          int response = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to logout?",
            "Logout Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            dispose(); // Close current window
            new LoginView().setVisible(true); // Open login form
        }

    }//GEN-LAST:event_LogoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingView("user@example.com").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookingBtn;
    private javax.swing.JButton ChangePasswordBtn;
    private javax.swing.JButton DashboardBtn;
    private javax.swing.JButton DeleteAccountBtn;
    private javax.swing.JButton EventBtn;
    private javax.swing.JButton HostoryBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton RatingBtn;
    private javax.swing.JButton SettingBtn;
    private javax.swing.JButton UpdateInfoBtn;
    private javax.swing.JButton ViewprofileBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
